### ISSUE TITLE
working but with errors on Giants Patch 1.4.1.0

### ISSUE THREAD

**Issue by HurrycaneBE** [VertexDezign/ParkVehicle#12] opened 2022-04-19 12:48 UTC
Hey Guys ,
this mod does no longer work on Patch 1.4 from Giants. 
Is there a Chance to fix it ?

**Comment by Grisu118** [comment] 2022-04-19 13:12
This is known, giants already has a hotfix in the pipeline
> Chaki 🐺 Community Cowordinator — heute um 13:31 Uhr
Thanks to your reports we discovered the cause of an issue with scriptmods and will deploy a hotfix as soon as possible.

**Comment by HurrycaneBE** [comment] 2022-04-21 12:16
okay , hotfix online , but the script gives an error - but it works.

2022-04-21 12:13   Load mod: FS22_park_vehicle
2022-04-21 12:13   Error: Invalid customEnvironment given for SpecializationManager.addSpecialization. Should be a string or nil.
2022-04-21 12:13 LUA call stack:
  dataS/scripts/mods.lua (396) : printCallstack
  =C:/Users/Administrator/Documents/My Games/FarmingSimulator2022/mods/FS22_park_vehicle/addSpecialization.lua (230) : addSpecialization
  =[C] (4294967295)
  dataS/scripts/mods.lua (347) : source
  dataS/scripts/mods.lua (839) : source
  dataS/scripts/xml/XMLFile.lua (296) : closure
  dataS/scripts/mods.lua (836) : iterate
  dataS/scripts/gui/MPLoadingScreen.lua (754) : loadMod
  dataS/scripts/misc/AsyncTaskManager.lua (41) : lambda
  dataS/scripts/misc/AsyncTaskManager.lua (120) : runLambda
  dataS/scripts/misc/AsyncTaskManager.lua (146) : runTopTask
  dataS/scripts/main.lua (1152) : update
2022-04-21 12:13   Error: Too .... REPEAT ERROR

**Comment by Grisu118** [comment] 2022-04-23 14:54
Issue is fixed with #13, you can use the zip linked there until it is available on modhub

**Closed as completed** 2022-04-27 14:26 UTC
Labels: bug
